name: CI
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: Windows
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 5.0.x
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: msbuild src -p:Configuration=Release -restore -m
      - name: Upload assets
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Assets
          path: src/NServiceBus.PowerShell/bin/Release
          retention-days: 7
      - name: Run tests
        uses: Particular/run-tests-action@v1.0.0
